
site_name: Pantogether
site_url: https://pantogether.fr
repo_url: https://github.com/CHU-Brest/pantogether
edit_uri: edit/main/docs/
nav:
  - Accueil: index.md
  - Patients: 
    - patients/informations.md
    - patients/associations.md
    - patients/communications.md
    - patients/webconferences.md
    - patients/lexique.md
    - patients/evenements.md
  - Cartes int√©ractives :
    - cartes.html
  - Les centres experts:
    - reseau/fvb.md
  - data/essais_cliniques.json
  - index.html
  - Recherche:
    - recherche/essaiscliniques.html
    - recherche/registre.md
    - recherche/travaux.md
  - RCP:
    - rcp/fvb.md
  - Ressources : 
    - ressources/recommandations.md
  - Agenda:
    - agenda/evenements.md
    - agenda/formations.md
  - Contact:
    - contact/contact.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 3

extra:
  meta:
    - name: robots
      content: noindex, nofollow
  

theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - content.action.edit
